apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app
        image: backend
        ports:
        - containerPort: 3000
