apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: episode2:latest
        ports:
        - containerPort: 80
